### ISSUE TITLE
feat: show camera preview in div

### ISSUE THREAD

**Issue by mburger81** [Cap-go/capacitor-camera-preview#103]
We are trying your camera preview plugin.

Actually we are using the @teamhive/capacitor-video-recorder plugin where we can show the video output during video recording in a DIV on our ionic app. 

Looking on your documentation I can not see such a functionality, is this correct? Is it possible you can implement a feature like this?

thx

**Comment by riderx** [comment]
Could be, I have to check, are you up to supporting the dev of it?

**Comment by riderx** [comment]
you can choose the x/y and size so i would say yes
