### ISSUE TITLE
Throwng error `capture()` and `startRecording()` in android 14

### ISSUE THREAD

**Issue by Saqib92** [Cap-go/capacitor-camera-preview#107]
Throwing error when trying any method:

`{message: 'Camera is not running'}`

```
async recordVid() {
    try {
      let opt: CameraPreviewOptions = {
        position: 'front',
        width: window.screen.width,
        height: window.screen.height
      }
      await CameraPreview.startRecordVideo(opt)
      
      await new Promise(resolve => setTimeout(resolve, 5000))

      const fileUrl = await CameraPreview.stopRecordVideo()
      console.log(fileUrl)
      
    }
    catch (err) {
      console.log(err)
    }

  }
```

Getting this error:

![Screenshot 2024-09-09 at 2 01 42 PM](https://github.com/user-attachments/assets/4b7b6334-9952-4080-9e9d-c445ae2d733c)

Added permissions in manifest:

```
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

**Comment by WcaleNieWolny** [comment]
@Saqib92 the code you shared does not correspond to the error you shared. In either way, I would recommend doing the following inside of the component you use for the camera:

```ts
// vue.js specific code
onUnmounted(async () => {
  await CameraPreview.stop() // <-- important, stop the camera when you unmount
})


onMounted(() => {
  await CameraPreview.start({
    toBack: true,
    parent: 'cam-prev'
  })
})
```

Personally, I was experiencing a similar errors to yours, but this `CameraPreview.stop` call helped me resolve it

**Comment by Saqib92** [comment]
> @Saqib92 the code you shared does not correspond to the error you shared. In either way, I would recommend doing the following inside of the component you use for the camera:
> 
> ```ts
> // vue.js specific code
> onUnmounted(async () => {
>   await CameraPreview.stop() // <-- important, stop the camera when you unmount
> })
> 
> 
> onMounted(() => {
>   await CameraPreview.start({
>     toBack: true,
>     parent: 'cam-prev'
>   })
> })
> ```
> 
> Personally, I was experiencing a similar errors to yours, but this `CameraPreview.stop` call helped me resolve it

Yes, i found this `stop()` method helpful.
