### ISSUE TITLE
Need Video Recording for iOS.

### ISSUE THREAD

**Issue by Saqib92** [Cap-go/capacitor-camera-preview#2]
are we getting video recording in iOS?

**Comment by riderx** [comment]
Yes as in android

**Comment by Saqib92** [comment]
> Yes as in android

any ETA?

**Comment by riderx** [comment]
Sorry my answer was "yes that work like android already", i just saw the doc was not updated, IOS is implemented

**Comment by Saqib92** [comment]
> Sorry my answer was "yes that work like android already", i just saw the doc was not updated, IOS is implemented

Okay i will test it and let you know.

**Comment by Saqib92** [comment]
![Screenshot 2022-12-14 at 1 56 58 PM](https://user-images.githubusercontent.com/7135885/207551195-ae8031c9-9356-423f-be5a-21c82c3794d6.png)
Video Recording not working.

**Comment by riderx** [comment]
Seems the definition was broken, after PR merge, i fixxed it

**Comment by Saqib92** [comment]
Still showing same error. Please update npm package so I can install/test new version.

**Comment by riderx** [comment]
sorry released it, but forgot to tell you, did you checked ?

**Comment by Saqib92** [comment]
No, Will check and let you know. thanks,
