### ISSUE TITLE
Can't get the same size with the preview as with the captureSample

### ISSUE THREAD

**Issue by FernetB** [Cap-go/capacitor-camera-preview#24]
I can't match 100% the preview size with the capturaSample size (with capture is even worse)

Currently I start the preview with only 
```js
 position: "rear",
 toBack: true,
```
and captureSame method with
```js
 quality: 100,
```

You can see the difference in the head of the bottle
(<img /> tag, that has the picture is full screen, is not cropped) 
Preview:
![image](https://user-images.githubusercontent.com/47339424/217316510-34d401d4-c65a-4523-b306-8e9c9fd2643b.png)

Photo:
![image](https://user-images.githubusercontent.com/47339424/217316562-c50779eb-2693-4cbe-92cf-9b3c846145e1.png)

**Comment by FernetB** [comment]
@riderx is this repo still mantained?

**Comment by riderx** [comment]
yes i was just in vacation,

thanks for the report, i'm not sure to understand your issue, the photo taken is not the same size than the preview ?

**Comment by FernetB** [comment]
Oh sorry for the trouble!

There are 2 problems:

 - Capture: this takes a native picture, and depending on the phone, sometimes the picture is taken with another lens, and therefore the photo does not match what you were seeing on the preview
 - CaptureSample: this take a frame from the preview, but for me does not match exactly the preview. In the two bottle's pictures you can see that the bottle cap is visible on the first picture (the preview) and is sliced on the second picture (the captureSample)

I hope I have explained myself correctly

**Comment by kenjoesavandal** [comment]
@FernetB did you find a fix? I have the same issue. :(

**Comment by riderx** [comment]
Hey guys, i finally took a look thanks for reporting it, it should be fixed now !

**Comment by riderx** [comment]
i didn't touched CaptureSample, but fixed Capture
