### ISSUE TITLE
Feat: RECORD_AUDIO Permission shouldn't be required

### ISSUE THREAD

**Issue by qliqdev** [Cap-go/capacitor-camera-preview#75]
Hi. What if we use camera preview only for taking photos.

Is it possible to dynamicaly check and request `RECORD_AUDIO` permission even if client calls `startRecordVideo` function?

**Comment by selected-pixel-jameson** [comment]
Ya. This needs to be removed. This is a huge issue. It's really screwed me with a recent deployment as I didn't realize this permission got added and it's most definitely not needed just to take a picture.

**Comment by riderx** [comment]
We will fix it thanks for the feedback

**Comment by riderx** [comment]
@qliqdev did you set `disableAudio` to true when you call the plugin?

**Comment by riderx** [comment]
We published a fix for Android, it was missing on android please try [6.5.0](https://github.com/Cap-go/camera-preview/tree/refs/tags/6.5.0)

**Comment by qliqdev** [comment]
> We published a fix for Android, it was missing on android please try [6.5.0](https://github.com/Cap-go/camera-preview/tree/refs/tags/6.5.0)

Thx a lot
